name: Assignment_12

on:
  push:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      FIB_INPUT: 10
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
        
      - name: Install with npm
        run: npm install
        
      - run: npm ci
      - run: npm run build
      
      - name: Deploy
        uses: peaceiris.actions-gh-pages@v3
